# Generated by Django 3.0.6 on 2020-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='default.jpg', max_length=200),
        ),
    ]
